spring.application.name=portfolio

%PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_portfolio
spring.datasource.username=user_name
spring.datasource.password=user_password

%Driver
spring.datasource.driver-class-name=org.postgresql.Driver

%JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true

%PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

%Server
server.port=8080

# User (Avoiding user entity as only I will have the access to modify any details)
portfolio.admin.username=user_name
portfolio.admin.password=user_password
portfolio.admin.role=user_role